// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtCHm9EN8kjybnM2RVex11-fyCfwGkn7M',
    appId: '1:696352642194:web:7f7beed3de1d477806c24b',
    messagingSenderId: '696352642194',
    projectId: 'servino-85dab',
    authDomain: 'servino-85dab.firebaseapp.com',
    storageBucket: 'servino-85dab.firebasestorage.app',
    measurementId: 'G-PZ27NW2D8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOh_2bIC-ldRQ-QsUoD0osMo3dMkkN_1o',
    appId: '1:696352642194:android:8086f6fce8beddc406c24b',
    messagingSenderId: '696352642194',
    projectId: 'servino-85dab',
    storageBucket: 'servino-85dab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1weWTYRFxu5rnKUuq6KMVhvxRdkHO0RY',
    appId: '1:696352642194:ios:d113207705601abb06c24b',
    messagingSenderId: '696352642194',
    projectId: 'servino-85dab',
    storageBucket: 'servino-85dab.firebasestorage.app',
    iosBundleId: 'online.walidghubara.servino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1weWTYRFxu5rnKUuq6KMVhvxRdkHO0RY',
    appId: '1:696352642194:ios:c7b98bc82ce36c3506c24b',
    messagingSenderId: '696352642194',
    projectId: 'servino-85dab',
    storageBucket: 'servino-85dab.firebasestorage.app',
    iosBundleId: 'com.example.servinoClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtCHm9EN8kjybnM2RVex11-fyCfwGkn7M',
    appId: '1:696352642194:web:80fa06b88203484206c24b',
    messagingSenderId: '696352642194',
    projectId: 'servino-85dab',
    authDomain: 'servino-85dab.firebaseapp.com',
    storageBucket: 'servino-85dab.firebasestorage.app',
    measurementId: 'G-Y8DSH8QL09',
  );
}
